name: SquidSaver
version: 0.0.4
author: Xenapte
main: info.bcrc.mc.squid_saver.SquidSaverPlugin
api-version: 1.13   # 1.13 for cross-version compatibility
commands:
  squid:
    description: SquidSaver plugin settings.
    usage: /squid || /squid setinterval <interval> || /squid reload
    permission: squidsaver.permission
    permission-message: You don't have the permission to run this command! 