name: SquidSaver
version: 0.0.1
author: Xenapte
main: info.bcrc.mc.squid_saver.Main
api-version: 1.17
commands:
  squid:
    description: SquidSaver plugin settings.
    usage: /squid || /squid <setinterval> <interval> || /squid reload
    permission: squidsaver.permission
    permission-message: You don't have the permission to run this command! 